version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
        - 5432:5432
  adminer:
    image: adminer
    restart: always
    depends_on :
      - postgres
    ports:
      - 8080:8080